/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTariffsRouteImport } from './routes/_authenticated/tariffs'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCashRouteImport } from './routes/_authenticated/cash'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedShipmentsIndexRouteImport } from './routes/_authenticated/shipments.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedCashIndexRouteImport } from './routes/_authenticated/cash.index'
import { Route as ApiFileSplatRouteImport } from './routes/api/file.$'
import { Route as AuthenticatedShipmentsNewRouteImport } from './routes/_authenticated/shipments.new'
import { Route as AuthenticatedReportsKudirRouteImport } from './routes/_authenticated/reports.kudir'
import { Route as AuthenticatedReportsBookRouteImport } from './routes/_authenticated/reports.book'
import { Route as AuthenticatedPartnerIdRouteImport } from './routes/_authenticated/partner.$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedCashNewRouteImport } from './routes/_authenticated/cash.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTariffsRoute = AuthenticatedTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashRoute = AuthenticatedCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShipmentsIndexRoute =
  AuthenticatedShipmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShipmentsRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedCashIndexRoute = AuthenticatedCashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCashRoute,
} as any)
const ApiFileSplatRoute = ApiFileSplatRouteImport.update({
  id: '/api/file/$',
  path: '/api/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShipmentsNewRoute =
  AuthenticatedShipmentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedShipmentsRoute,
  } as any)
const AuthenticatedReportsKudirRoute =
  AuthenticatedReportsKudirRouteImport.update({
    id: '/kudir',
    path: '/kudir',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsBookRoute =
  AuthenticatedReportsBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPartnerIdRoute = AuthenticatedPartnerIdRouteImport.update({
  id: '/partner/$id',
  path: '/partner/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedInvoicesRoute,
} as any)
const AuthenticatedCashNewRoute = AuthenticatedCashNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cash': typeof AuthenticatedCashRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/partners': typeof AuthenticatedPartnersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipments': typeof AuthenticatedShipmentsRouteWithChildren
  '/stock': typeof AuthenticatedStockRoute
  '/tariffs': typeof AuthenticatedTariffsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/cash/new': typeof AuthenticatedCashNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/partner/$id': typeof AuthenticatedPartnerIdRoute
  '/reports/book': typeof AuthenticatedReportsBookRoute
  '/reports/kudir': typeof AuthenticatedReportsKudirRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/cash/': typeof AuthenticatedCashIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tariffs': typeof AuthenticatedTariffsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/cash/new': typeof AuthenticatedCashNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/partner/$id': typeof AuthenticatedPartnerIdRoute
  '/reports/book': typeof AuthenticatedReportsBookRoute
  '/reports/kudir': typeof AuthenticatedReportsKudirRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/cash': typeof AuthenticatedCashIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/shipments': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cash': typeof AuthenticatedCashRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRouteWithChildren
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/tariffs': typeof AuthenticatedTariffsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/_authenticated/cash/new': typeof AuthenticatedCashNewRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/partner/$id': typeof AuthenticatedPartnerIdRoute
  '/_authenticated/reports/book': typeof AuthenticatedReportsBookRoute
  '/_authenticated/reports/kudir': typeof AuthenticatedReportsKudirRoute
  '/_authenticated/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/_authenticated/cash/': typeof AuthenticatedCashIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/cash'
    | '/dashboard'
    | '/invoices'
    | '/partners'
    | '/products'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/stock'
    | '/tariffs'
    | '/team'
    | '/api/realtime'
    | '/cash/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/partner/$id'
    | '/reports/book'
    | '/reports/kudir'
    | '/shipments/new'
    | '/api/file/$'
    | '/cash/'
    | '/invoices/'
    | '/reports/'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/partners'
    | '/products'
    | '/settings'
    | '/stock'
    | '/tariffs'
    | '/team'
    | '/api/realtime'
    | '/cash/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/partner/$id'
    | '/reports/book'
    | '/reports/kudir'
    | '/shipments/new'
    | '/api/file/$'
    | '/cash'
    | '/invoices'
    | '/reports'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/cash'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/partners'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shipments'
    | '/_authenticated/stock'
    | '/_authenticated/tariffs'
    | '/_authenticated/team'
    | '/api/realtime'
    | '/_authenticated/cash/new'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/partner/$id'
    | '/_authenticated/reports/book'
    | '/_authenticated/reports/kudir'
    | '/_authenticated/shipments/new'
    | '/api/file/$'
    | '/_authenticated/cash/'
    | '/_authenticated/invoices/'
    | '/_authenticated/reports/'
    | '/_authenticated/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiFileSplatRoute: typeof ApiFileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tariffs': {
      id: '/_authenticated/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof AuthenticatedTariffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash': {
      id: '/_authenticated/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AuthenticatedCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments/': {
      id: '/_authenticated/shipments/'
      path: '/'
      fullPath: '/shipments/'
      preLoaderRoute: typeof AuthenticatedShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedShipmentsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/cash/': {
      id: '/_authenticated/cash/'
      path: '/'
      fullPath: '/cash/'
      preLoaderRoute: typeof AuthenticatedCashIndexRouteImport
      parentRoute: typeof AuthenticatedCashRoute
    }
    '/api/file/$': {
      id: '/api/file/$'
      path: '/api/file/$'
      fullPath: '/api/file/$'
      preLoaderRoute: typeof ApiFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shipments/new': {
      id: '/_authenticated/shipments/new'
      path: '/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof AuthenticatedShipmentsNewRouteImport
      parentRoute: typeof AuthenticatedShipmentsRoute
    }
    '/_authenticated/reports/kudir': {
      id: '/_authenticated/reports/kudir'
      path: '/kudir'
      fullPath: '/reports/kudir'
      preLoaderRoute: typeof AuthenticatedReportsKudirRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/book': {
      id: '/_authenticated/reports/book'
      path: '/book'
      fullPath: '/reports/book'
      preLoaderRoute: typeof AuthenticatedReportsBookRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/partner/$id': {
      id: '/_authenticated/partner/$id'
      path: '/partner/$id'
      fullPath: '/partner/$id'
      preLoaderRoute: typeof AuthenticatedPartnerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/cash/new': {
      id: '/_authenticated/cash/new'
      path: '/new'
      fullPath: '/cash/new'
      preLoaderRoute: typeof AuthenticatedCashNewRouteImport
      parentRoute: typeof AuthenticatedCashRoute
    }
  }
}

interface AuthenticatedCashRouteChildren {
  AuthenticatedCashNewRoute: typeof AuthenticatedCashNewRoute
  AuthenticatedCashIndexRoute: typeof AuthenticatedCashIndexRoute
}

const AuthenticatedCashRouteChildren: AuthenticatedCashRouteChildren = {
  AuthenticatedCashNewRoute: AuthenticatedCashNewRoute,
  AuthenticatedCashIndexRoute: AuthenticatedCashIndexRoute,
}

const AuthenticatedCashRouteWithChildren =
  AuthenticatedCashRoute._addFileChildren(AuthenticatedCashRouteChildren)

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsBookRoute: typeof AuthenticatedReportsBookRoute
  AuthenticatedReportsKudirRoute: typeof AuthenticatedReportsKudirRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsBookRoute: AuthenticatedReportsBookRoute,
  AuthenticatedReportsKudirRoute: AuthenticatedReportsKudirRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedShipmentsRouteChildren {
  AuthenticatedShipmentsNewRoute: typeof AuthenticatedShipmentsNewRoute
  AuthenticatedShipmentsIndexRoute: typeof AuthenticatedShipmentsIndexRoute
}

const AuthenticatedShipmentsRouteChildren: AuthenticatedShipmentsRouteChildren =
  {
    AuthenticatedShipmentsNewRoute: AuthenticatedShipmentsNewRoute,
    AuthenticatedShipmentsIndexRoute: AuthenticatedShipmentsIndexRoute,
  }

const AuthenticatedShipmentsRouteWithChildren =
  AuthenticatedShipmentsRoute._addFileChildren(
    AuthenticatedShipmentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCashRoute: typeof AuthenticatedCashRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRouteWithChildren
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTariffsRoute: typeof AuthenticatedTariffsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedPartnerIdRoute: typeof AuthenticatedPartnerIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCashRoute: AuthenticatedCashRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRouteWithChildren,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTariffsRoute: AuthenticatedTariffsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedPartnerIdRoute: AuthenticatedPartnerIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiFileSplatRoute: ApiFileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
